data:
  train_csv: "datasets/meassurements/ion_normalised/microarray_271225.csv"
  remove_feats: [C_44H_86NO_5Na+, C_44H_88PNO_8Na+, C_27H_46ONa+, C_14H_28O_2Na+, C_14H_28O_6Na+, C_16H_32O_7Na+, C_18H_36O_8Na+, C_20H_40O_9Na+, C_22H_44O_10Na+, C_21H_42O_11Na+, C_31H_62O_15Na+, C_22H_44O_11Na+, C_23H_46O_12Na+, C_24H_48O_12Na+, C_25H_50O_12Na+,  C_25H_50O_13Na+, C_27H_54O_13Na+, C_27H_54O_14Na+, C_29H_58O_14Na+, C_29H_58O_15Na+, C_37H_74O_18Na+, C_37H_74O_19Na+, C_35H_70O_18Na+, C_39H_78O_19Na+, C_35H_70O_17Na+, C_39H_78O_20Na+, C_33H_66O_16Na+, C_33H_66O_17Na+, C_41H_82O_20Na+, C_31H_62O_16Na+, C_41H_82O_21Na+, C_43H_86O_21Na+, C_43H_86O_22Na+, C_45H_90O_23Na+, C_47H_94O_23Na+, C_47H_94O_24Na+, C_49H_98O_24Na+, C_49H_98O_25Na+, C_47H_119O_12Na+, C_57H_131O_13Na+, C_48H_119O_14Na+, C_38H_80N+, C_14H_13PNO_4+, C_44H_88NO_5+, C_44H_89PNO_8+, C_26H_53PNO_6+, C_44H_85NO_4+, C_44H_85NO_5+]
  test_csv: "datasets/meassurements/ion_normalised/microarray_300126.csv"
  profile_csv: "datasets/profile/ion_normalised/profile.csv"
  curve_txt: "datasets/instrument/VAMAS_Instrument.txt"
  n_targets: 4
  dropna_test: true

scaling:
  instrument: [ "wsor", "none","log10"]
  experiment: ["none","minmax", "standard"]
  local: [true, false]

tuning:
  enabled: true
  n_trials: 10

training:
  random_state: [42, 43, 44, 45, 46]
  device: "auto"
  test_size: 0.2
  val_size: 0.2
  epochs: 300
  patience: 25
  batch_size: 256
  lr: 0.001
  weight_decay: 0.0001
  target_names: ["SM102", "DMGPEG", "DSPC", "Cholesterol"]

baseline:
  shuffle_targets: false

paths:
  runs: benchmarks
  benchmark: root

plotting:
  parity:
    markers: ["o", "s", "^", "D"]
    colors:
      SM102: "#1fa9a3"
      DMGPEG: "#e46c19"
      DSPC: "#8e73c7"
      Cholesterol: "#5fb13d"